const S=JSON.parse(localStorage.getItem('craftAtelier')||'{"projects":[]}');const save=()=>localStorage.setItem('craftAtelier',JSON.stringify(S));
const svg=n=>({home:'<path d="M3 11 12 3l9 8v9a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1z"/>',scissors:'<circle cx="6" cy="7" r="3"/><circle cx="6" cy="17" r="3"/><path d="m8.7 8.4 12.3 6.1M8.7 15.6 21 9.5"/>',book:'<path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20V4H6.5A2.5 2.5 0 0 0 4 6.5z"/><path d="M8 7h8M8 11h6"/>',box:'<path d="m4 7 8-4 8 4-8 4zM4 7v10l8 4 8-4V7M12 11v10"/>',spark:'<path d="m12 3 1.6 4.4L18 9l-4.4 1.6L12 15l-1.6-4.4L6 9l4.4-1.6zM19 16l.8 2.2L22 19l-2.2.8L19 22l-.8-2.2L16 19l2.2-.8z"/>',plus:'<path d="M12 5v14M5 12h14"/>',needle:'<path d="M20 4 8 16M17 3l4 4M5 19l3-3M3 21l2-2"/>',heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.6l-1-1a5.5 5.5 0 0 0-7.8 7.8l1 1L12 21l7.8-7.6 1-1a5.5 5.5 0 0 0 0-7.8z"/>',image:'<rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8.5" cy="8.5" r="1.5"/><path d="m21 15-5-5L5 21"/>'}[n]||'');const I=n=>`<svg viewBox="0 0 24 24">${svg(n)}</svg>`;
const labels={home:'アトリエ',projects:'制作',library:'図案庫',materials:'材料箱',guide:'基本'};const nav=a=>`<nav class="bottom">${Object.keys(labels).map(k=>`<button class="nav ${a===k?'active':''}" onclick="route('${k}')">${I({home:'home',projects:'scissors',library:'book',materials:'box',guide:'spark'}[k])}<span>${labels[k]}</span></button>`).join('')}</nav>`;
function route(p){location.hash=p;render()}window.route=route;
function home(){return `<div class="head"><div class="kicker">MY LITTLE WORKROOM</div><h1>Craft Atelier</h1><p class="sub">つくりたい気持ちを、ひとつのアトリエに。</p></div><section class="hero"><div class="hero-top"><div><h2>今日は何をつくる？</h2><p>ぬいも、編み物も、刺繍も。<br>資料から完成までここに残そう。</p></div><div class="hero-icon">${I('heart')}</div></div></section><section class="section"><div class="section-title"><h2>アトリエの引き出し</h2></div><div class="grid">${[['projects','scissors','制作プロジェクト','推しぬい・あみぐるみなどを設計'],['library','image','図案・型紙','拾った資料も出典つきで整理'],['materials','box','材料箱','布・毛糸・刺繍糸をメモ'],['guide','spark','手芸の基本','編み方・縫い方をすぐ確認']].map(x=>`<button class="card" onclick="route('${x[0]}')"><div class="ico">${I(x[1])}</div><h3>${x[2]}</h3><p>${x[3]}</p></button>`).join('')}</div></section><section class="section"><div class="section-title"><h2>制作中</h2></div>${S.projects.length?S.projects.map((p,i)=>`<div class="project"><div class="thumb">${I('needle')}</div><div style="flex:1"><h3>${p.name}</h3><p>${p.type} ・ ${p.note||'制作メモはまだありません'}</p><div class="progress"><span style="width:${p.progress||10}%"></span></div></div></div>`).join(''):`<div class="empty">まだ制作中の作品はありません。<br>最初のひとつを登録してみよう。</div>`}</section>${nav('home')}`}
function projects(){return `<div class="head"><div class="kicker">PROJECTS</div><h1>制作プロジェクト</h1><p class="sub">設計・資料・工程を作品ごとにまとめます。</p></div><div class="page">${S.projects.length?S.projects.map(p=>`<div class="project"><div class="thumb">${I('needle')}</div><div><h3>${p.name}</h3><p>${p.type}</p><div class="tags"><span>${p.progress||10}%</span></div></div></div>`).join(''):`<div class="empty">推しぬい、あみぐるみ、刺繍など<br>新しい制作を登録できます。</div>`}</div><button class="fab" onclick="route('new')">${I('plus')}</button>${nav('projects')}`}
function newProject(){return `<div class="head"><div class="kicker">NEW PROJECT</div><h1>新しい制作</h1></div><div class="page"><label class="field">作品名<input id="pn" placeholder="例：玲王ぬい"></label><label class="field">種類<select id="pt"><option>推しぬい</option><option>あみぐるみ</option><option>編み物</option><option>刺繍</option><option>裁縫</option><option>アクセサリー</option><option>その他</option></select></label><label class="field">ひとことメモ<textarea id="pm" placeholder="作りたい雰囲気、サイズなど"></textarea></label><button class="primary" onclick="addProject()">アトリエに追加</button></div>${nav('projects')}`}
window.addProject=()=>{const n=document.querySelector('#pn').value.trim();if(!n)return;S.projects.unshift({name:n,type:document.querySelector('#pt').value,note:document.querySelector('#pm').value,progress:10});save();route('projects')};
function simple(kind,title,sub,body){return `<div class="head"><div class="kicker">CRAFT ATELIER</div><h1>${title}</h1><p class="sub">${sub}</p></div><div class="page">${body}</div>${nav(kind)}`}
function render(){let p=location.hash.slice(1)||'home',html;if(p==='home')html=home();else if(p==='projects')html=projects();else if(p==='new')html=newProject();else if(p==='library')html=simple('library','図案・型紙ライブラリ','参考資料を、あとで迷子にしない。','<div class="empty">画像・PDF・URLを保存する場所。<br>「目」「髪」「衣装」「編み図」などのタグと<br>作者・出典・利用条件も一緒に管理する予定です。</div>');else if(p==='materials')html=simple('materials','材料箱','持っている素材を小さな棚みたいに。','<div class="grid"><div class="card"><div class="ico">'+I('box')+'</div><h3>毛糸</h3><p>太さ・色・ロット・残量</p></div><div class="card"><div class="ico">'+I('needle')+'</div><h3>布・刺繍糸</h3><p>ぬい生地や糸番号を記録</p></div></div>');else html=simple('guide','手芸の基本','「これどうやるんだっけ？」をすぐ確認。','<div class="guide"><h3>かぎ針編み</h3><p>くさり編み／細編み／長編み／増し目・減らし目／輪の作り目。手順イラストを追加していく予定です。</p></div><div class="guide"><h3>ぬい・裁縫</h3><p>玉結び／返し縫い／まつり縫い／顔刺繍の基本。制作画面からも呼び出せる図鑑に育てます。</p></div>');document.querySelector('#app').innerHTML='<div class="app">'+html+'</div>'}window.addEventListener('hashchange',render);render();
